spring:
  application:
    name: parvis-server
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never # auto-create tables if not exist
    timeout: 60m
  servlet:
    session:
      cookie:
        name: SESSIONID
        http-only: true
        secure: false  # make true in production
        same-site: none
  mvc:
    throw-exception-if-no-handler-found:

logging:
  level:
    org.springframework.session.jdbc: DEBUG
#    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
